Add Trustworthy Mod
LumpBloom7/hishigata pull request #175
Opened 2022-11-03 21:23 UTC by PillTime

Added a mod that disables feign notes.
I had never touched C# before, so I checked https://github.com/taulazer/tau to see how to write mods.
I set the score to 80% because the mod makes the beatmaps easier, but I'm not sure if that's the best multiplier.

2022-11-03 21:31 UTC, LumpBloom7 requested changes
Looks good overall. Some leftover comments need to be removed.

In addition, a resx file needs to be created in resource for the strings used in TW, since that is where the localised strings are fetched from (also makes the string visible in crowdin).

2022-11-03 21:31 UTC, LumpBloom7 commented on osu.Game.Rulesets.Hishigata/Mods/HishigataModTrustworthy.cs
> +        //public override bool UserPlayable => true;
Remove these comments

2022-11-03 21:31 UTC, LumpBloom7 commented on osu.Game.Rulesets.Hishigata/Mods/HishigataModTrustworthy.cs
> +        //public override bool HasImplementation => true;
As above

2022-11-03 22:01 UTC, PillTime commented
I copied the resx file that was already there for the hidden mod and changed the value, not sure if anything else should be done.

2022-11-04 12:15 UTC, LumpBloom7 approved these changes
LGTM. Everything seems to be in order.

2022-11-07 20:58 UTC, merged